Repository TechSkill-repo/SH-Constructions-IMS-, pull requests merged in 2022-09, with the labels that each got.

#23 Loan Feature
  backend/app.js
  backend/controllers/issue.controllers.js
  backend/controllers/loan.controllers.js
  backend/controllers/request.controllers.js
  backend/controllers/socket.controllers.js
  backend/controllers/store.controllers.js
  backend/package-lock.json
  backend/package.json
  backend/routes/loan.routes.js
  backend/routes/store.routes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/NotificationsDropdown.js
  frontend/src/pages/auth/Login.js
  frontend/src/pages/dashboards/Central/MonitorLone/MonitorLone.js
  frontend/src/pages/dashboards/Site/Inventory/Consumable.js
  frontend/src/pages/dashboards/Site/Inventory/NonConsumable.js
  frontend/src/pages/dashboards/Site/LoanApprove/ApprovedLone/ApprovedLone.js
  frontend/src/pages/dashboards/Site/LoanApprove/LoanApproveTable.js
  frontend/src/pages/dashboards/Site/LoanReqTable/LoanReqTable.js
  frontend/src/pages/dashboards/Site/LoanRequest/LoanRequest.js
  frontend/src/pages/dashboards/Site/LoanRequest/Popup.js
  frontend/src/services/loanService.js
  frontend/src/services/socketService.js
  frontend/src/services/storeService.js
Labels: bug, enhancement, files

#28 all products
  backend/controllers/material.controllers.js
  backend/routes/material.routes.js
  frontend/src/pages/dashboards/Central/AllProducts/Allproducts.js
  frontend/src/routes/centralStore.js
  frontend/src/services/materialService.js
Labels: enhancement

#32 Changes in critical tools
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/dashboards/Central/CriticalTools/CriticalTools.js
  frontend/src/pages/dashboards/Central/CriticalTools/CriticalToolsForm.js
  frontend/src/pages/dashboards/Central/CriticalTools/CriticalToolsTable.js
Labels: bug, enhancement
